version: '3'

tasks:
  installdeps:
    desc: Instala las dependencias del proyecto.
    cmds:
      - go mod download

  updatedeps:
    desc: Actualiza las dependencias del proyecto.
    cmds:
      - go get
  
  build:
    desc: Compila el proyecto.
    cmds:
      - go build

  check:
    desc: Comprueba la sintaxis del proyecto.
    cmds:
      - gofmt -e ./pkg/ > /dev/null
     
  test:
    desc: Ejecuta los tests del proyecto.
    cmds:
      - go test -v ./pkg/
